In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/Users/pintoza/Desktop/dev/data-science/sales_optimization/data/processed/df_final.csv")

In [4]:
daily_demand = df.groupby(['product_id', 'order_date'])['order_quantity'].sum().reset_index()
daily_demand

      product_id  order_date  order_quantity
0              1  2018-05-31               5
1              1  2018-06-02               7
2              1  2018-06-03               1
3              1  2018-06-06               1
4              1  2018-06-09               1
...          ...         ...             ...
7311          47  2020-11-26              15
7312          47  2020-12-05              10
7313          47  2020-12-08               7
7314          47  2020-12-12               1
7315          47  2020-12-24               3

[7316 rows x 3 columns]

In [7]:
# Convert to datetime format
df['order_date'] = pd.to_datetime(df['order_date'])
df['delivery_date'] = pd.to_datetime(df['delivery_date'])

# Compute lead time
df['lead_time'] = (df['delivery_date'] - df['order_date']).dt.days
df.head()

,order_number,sales_channel,warehouse_code,procured_date,order_date,ship_date,delivery_date,sales_team_id,customer_id,store_id,...,unit_price,Month,Quarter,Discounted_Price,Time_to_Delivery,Customer_Lifetime_Value,Product_Popularity,Weekday,Stock_Turnover_Ratio,lead_time
0,101,In-Store,4,2017-12-31,2018-05-31,2018-06-14,2018-06-19,6,15,259,...,1963,5,2,1815.775,19,346917,181,True,0.000138,19
1,102,Online,3,2017-12-31,2018-05-31,2018-06-22,2018-07-02,14,20,196,...,3940,5,2,3644.500,32,343797,190,True,0.000083,32
2,103,Distributor,4,2017-12-31,2018-05-31,2018-06-21,2018-07-01,21,16,213,...,1776,5,2,1687.200,31,331117,177,True,0.000028,31
3,104,Wholesale,3,2017-12-31,2018-05-31,2018-06-02,2018-06-07,28,48,107,...,2325,5,2,2150.625,7,368867,194,True,0.000221,7
4,105,Distributor,3,2018-04-10,2018-05-31,2018-06-16,2018-06-26,22,49,111,...,1822,5,2,1639.800,26,346776,158,True,0.000221,26

In [9]:
avg_demand_lead_time = df.groupby('product_id').agg(
    avg_daily_demand=('order_quantity', 'mean'),
    avg_lead_time=('lead_time', 'mean')
).reset_index()

avg_demand_lead_time

    product_id  avg_daily_demand  avg_lead_time
0            1          4.203704      20.753086
1            2          4.734104      21.173410
2            3          4.441860      21.308140
3            4          4.390000      20.105000
4            5          4.687861      19.797688
5            6          4.305195      22.097403
6            7          4.427711      20.186747
7            8          4.507692      19.835897
8            9          4.541176      20.823529
9           10          4.494048      21.005952
10          11          4.472527      20.994505
11          12          4.569061      21.215470
12          13          4.440000      20.537143
13          14          4.699387      19.975460
14          15          4.191083      20.929936
15          16          4.598870      22.299435
16          17          4.533708      20.606742
17          18          4.128205      20.403846
18          19          4.707317      20.463415
19          20          4.694118      20.841176
20          21          4.696429      21.517857
21          22          4.982143      20.761905
22          23          4.927835      20.505155
23          24          4.656442      18.865031
24          25          4.494444      19.983333
25          26          4.575949      20.575949
26          27          4.368421      21.242105
27          28          4.544944      20.410112
28          29          4.647727      20.386364
29          30          4.205128      20.878205
30          31          4.544379      19.781065
31          32          4.551724      20.806897
32          33          4.186747      21.222892
33          34          4.177632      20.269737
34          35          4.583333      20.839286
35          36          4.523529      21.647059
36          37          4.480000      21.205000
37          38          4.546448      20.628415
38          39          4.371951      19.774390
39          40          4.646739      21.059783
40          41          4.770950      21.558659
41          42          4.435374      20.326531
42          43          4.672727      19.987879
43          44          4.642857      19.976190
44          45          4.569767      19.604651
45          46          4.489011      21.467033
46          47          4.473684      20.644737

In [10]:
std_dev_daily_demand = daily_demand.groupby('product_id')['order_quantity'].std().reset_index()
std_dev_daily_demand.columns = ['product_id', 'std_dev_daily_demand']

std_dev_daily_demand

    product_id  std_dev_daily_demand
0            1              2.932415
1            2              2.861648
2            3              3.187047
3            4              2.896343
4            5              2.825124
5            6              2.636330
6            7              2.794410
7            8              2.856660
8            9              2.237435
9           10              2.650616
10          11              3.020526
11          12              2.488064
12          13              2.670610
13          14              2.690971
14          15              2.566779
15          16              2.857947
16          17              2.795669
17          18              2.760617
18          19              2.757264
19          20              2.802512
20          21              2.688663
21          22              3.001345
22          23              2.779595
23          24              2.838781
24          25              2.860165
25          26              2.658807
26          27              2.915898
27          28              2.853326
28          29              2.436635
29          30              2.878456
30          31              2.760570
31          32              2.725875
32          33              3.014680
33          34              2.775702
34          35              2.637091
35          36              2.477428
36          37              2.779441
37          38              3.294020
38          39              2.289767
39          40              2.717282
40          41              2.832631
41          42              3.097848
42          43              2.497922
43          44              2.468499
44          45              2.588180
45          46              2.964847
46          47              2.544362

In [11]:
df['lead_time_demand'] = df['lead_time'] * df['order_quantity']
std_dev_lead_time_demand = df.groupby('product_id')['lead_time_demand'].std().reset_index()
std_dev_lead_time_demand.columns = ['product_id', 'std_dev_lead_time_demand']

std_dev_lead_time_demand

    product_id  std_dev_lead_time_demand
0            1                 62.236065
1            2                 66.903744
2            3                 62.985939
3            4                 59.719692
4            5                 64.948523
5            6                 64.095394
6            7                 62.686535
7            8                 68.069097
8            9                 61.123143
9           10                 65.910888
10          11                 58.051706
11          12                 65.569051
12          13                 63.701239
13          14                 68.932986
14          15                 63.855742
15          16                 66.731392
16          17                 66.498423
17          18                 64.223706
18          19                 64.359951
19          20                 63.089553
20          21                 61.184119
21          22                 64.585269
22          23                 61.401252
23          24                 60.000495
24          25                 62.598256
25          26                 61.421299
26          27                 64.051260
27          28                 67.575089
28          29                 63.340166
29          30                 58.715414
30          31                 68.237767
31          32                 58.862044
32          33                 62.651944
33          34                 62.512972
34          35                 64.218548
35          36                 68.081067
36          37                 64.000885
37          38                 62.778979
38          39                 64.498040
39          40                 64.320634
40          41                 63.595819
41          42                 61.900936
42          43                 57.160098
43          44                 65.754658
44          45                 62.207656
45          46                 68.133176
46          47                 60.076621

In [12]:
merged_data = avg_demand_lead_time.merge(std_dev_daily_demand, on='product_id').merge(std_dev_lead_time_demand, on='product_id')

Z = 1.645
merged_data['safety_stock'] = (Z * merged_data['std_dev_lead_time_demand']) - (merged_data['avg_daily_demand'] * merged_data['avg_lead_time'] - merged_data['avg_daily_demand'])

merged_data

,product_id,avg_daily_demand,avg_lead_time,std_dev_daily_demand,std_dev_lead_time_demand,safety_stock
0,1,4.203704,20.753086,2.932415,62.236065,19.342205
1,2,4.734104,21.173410,2.861648,66.903744,14.553635
2,3,4.441860,21.308140,3.187047,62.985939,13.405947
3,4,4.390000,20.105000,2.896343,59.719692,14.367943
4,5,4.687861,19.797688,2.825124,64.948523,18.719367
5,6,4.305195,22.097403,2.636330,64.095394,14.608495
6,7,4.427711,20.186747,2.794410,62.686535,18.165982
7,8,4.507692,19.835897,2.856660,68.069097,27.067234
8,9,4.541176,20.823529,2.237435,61.123143,10.525425
9,10,4.494048,21.005952,2.650616,65.910888,18.515708
10,11,4.472527,20.994505,3.020526,58.051706,6.069080
11,12,4.569061,21.215470,2.488064,65.569051,15.495379
12,13,4.440000,20.537143,2.670610,63.701239,18.043623
13,14,4.699387,19.975460,2.690971,68.932986,24.221741
14,15,4.191083,20.929936,2.566779,63.855742,21.514682
15,16,4.598870,22.299435,2.857947,66.731392,11.819805
16,17,4.533708,20.606742,2.795669,66.498423,20.498667
17,18,4.128205,20.403846,2.760617,64.223706,25.544939
18,19,4.707317,20.463415,2.757264,64.359951,14.251656
19,20,4.694118,20.841176,2.802512,63.089553,10.645498
20,21,4.696429,21.517857,2.688663,61.184119,4.287225
21,22,4.982143,20.761905,3.001345,64.585269,7.786134
22,23,4.927835,20.505155,2.779595,61.401252,4.886875
23,24,4.656442,18.865031,2.838781,60.000495,15.513340
24,25,4.494444,19.983333,2.860165,62.598256,17.654594
25,26,4.575949,20.575949,2.658807,61.421299,11.459485
26,27,4.368421,21.242105,2.915898,64.051260,16.938284
27,28,4.544944,20.410112,2.853326,67.575089,22.943152
28,29,4.647727,20.386364,2.436635,63.340166,14.092042
29,30,4.205128,20.878205,2.878456,58.715414,12.996455
30,31,4.544379,19.781065,2.760570,68.237767,26.902855
31,32,4.551724,20.806897,2.725875,58.862044,6.672533
32,33,4.186747,21.222892,3.014680,62.651944,18.394317
33,34,4.177632,20.269737,2.775702,62.512972,22.331978
34,35,4.583333,20.839286,2.637091,64.218548,14.709452
35,36,4.523529,21.647059,2.477428,68.081067,18.595777
36,37,4.480000,21.205000,2.779441,64.000885,14.763057
37,38,4.546448,20.628415,3.294020,62.778979,14.031849
38,39,4.371951,19.774390,2.289767,64.498040,24.018557
39,40,4.646739,21.059783,2.717282,64.320634,12.594866
40,41,4.770950,21.558659,2.832631,63.595819,6.530792
41,42,4.435374,20.326531,3.097848,61.900936,16.106645
42,43,4.672727,19.987879,2.497922,57.160098,5.303182
43,44,4.642857,19.976190,2.468499,65.754658,20.062670
44,45,4.569767,19.604651,2.588180,62.207656,17.312665
45,46,4.489011,21.467033,2.964847,68.133176,20.202339
46,47,4.473684,20.644737,2.544362,60.076621,10.941693

In [13]:
merged_data.to_csv("/Users/pintoza/Desktop/dev/data-science/sales_optimization/data/processed/inventory_optimization.csv", index=False)